
"""QB Chart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rIIHTO-49-JFJMrMi087oR4rrYuBJUUw
"""
import streamlit as st
st.title("QB Pass Chart V0.2")

import matplotlib.pyplot as plt
import pandas as pd
from matplotlib.lines import Line2D



# Función para dibujar el campo de fútbol
def draw_football_field(ax):
    ax.set_facecolor('black')
    ax.plot([0, 53.3, 53.3, 0, 0], [-10, -10, 60, 60, -10], color='white', linewidth=2)

    for y in range(-10, 61, 10):
        ax.axhline(y, color='white', linewidth=1)

    for y in [-5, 5, 15, 25, 35, 45, 55]:
        ax.axhline(y, color='white', linewidth=0.75, linestyle='-')

    for y in [-10, 10, 20, 30, 40, 50, 60]:
        ax.text(8, y-0.84, f"{y}", fontsize=15, color='white', ha='center', rotation=270, linespacing=3.2)
        ax.text(45, y-0.42, f"{y}", fontsize=15, color='white', ha='center', rotation=90, linespacing=3.2)

    for y in range(-10, 61):
        if y % 5 != 0:
            ax.plot([19, 20], [y, y], color='white', linewidth=1)
            ax.plot([33, 34], [y, y], color='white', linewidth=1)

# Función para graficar los pases filtrados
def plot_football_passes(df, down, distance_type, d1, d2, custom_title):
    # --- filtros ---
    if down != "All":
        df = df[df['DN'] == down]

    if distance_type == "Equal to":
        df = df[df['DIST'] == d1]
    elif distance_type == "Greater than":
        df = df[df['DIST'] >= d1]
    elif distance_type == "Less than":
        df = df[df['DIST'] <= d1]
    elif distance_type == "Between":
        df = df[(df['DIST'] >= d1) & (df['DIST'] <= d2)]

    # --- figura (SOLO UNA) ---
    fig, ax = plt.subplots(figsize=(8, 8))
    draw_football_field(ax)

    ax.set_xlim(0, 53.3)
    ax.set_ylim(-10, 60)
    ax.set_xticks([])
    ax.set_yticks([])
    ax.axhline(0, color='blue', linewidth=2)
    ax.set_aspect('equal')

    title = custom_title if custom_title else f"Pass Chart – Down {down}"
    ax.set_title(title)

    # --- puntos ---
    for _, row in df.iterrows():
        x = row['Target X 100']
        y = row['Target Y 100'] - row['SPOT Y 100']
        ax.scatter(x, y, color=row['Color'], s=80)

        if 'WR' in df.columns and not pd.isna(row['WR']):
            ax.text(x, y, str(int(row['WR'])), fontsize=6,
                    ha='center', va='center', color='black')

    # --- leyenda ---
    legend_elements = [
        Line2D([0], [0], marker='o', color='w', label='Completo', markerfacecolor='aqua', markersize=8),
        Line2D([0], [0], marker='o', color='w', label='Incompleto', markerfacecolor='fuchsia', markersize=8),
        Line2D([0], [0], marker='o', color='w', label='Intercepción', markerfacecolor='red', markersize=8),
        Line2D([0], [0], marker='o', color='w', label='Touchdown', markerfacecolor='lime', markersize=8),
        Line2D([0], [0], marker='o', color='w', label='Drop', markerfacecolor='yellow', markersize=8),
    ]
    leg = ax.legend(handles=legend_elements, loc='upper right',
                    frameon=True, facecolor='black', edgecolor='white')
    for t in leg.get_texts():
        t.set_color('white')

    # --- mostrar (SOLO UNA VEZ) ---
    st.pyplot(fig)

st.title("🏈 Pass Chart Interactivo")

uploaded_file = st.file_uploader("Sube tu archivo CSV o Excel", type=["csv", "xlsx"])

if uploaded_file:
    df = pd.read_csv(uploaded_file) if uploaded_file.name.endswith(".csv") else pd.read_excel(uploaded_file)
    df.columns = df.columns.str.strip()
    df = df.dropna(subset=['Target X 100', 'Target Y 100'])

    def get_color(row):
        if row['TD/INT'] == 'TD':
            return 'lime'
        elif row['TD/INT'] == 'INT':
            return 'red'
        elif row['TD/INT'] == 'Drop':
            return 'yellow'
        elif row['COM']:
            return 'aqua'
        else:
            return 'fuchsia'

    df['Color'] = df.apply(get_color, axis=1)

    # 🔹 Sidebar
    st.sidebar.header("Filtros")
    down = st.sidebar.selectbox("Down", ["All"] + sorted(df['DN'].unique()))
    distance_type = st.sidebar.selectbox(
        "Tipo de distancia", ["Equal to", "Greater than", "Less than", "Between"]
    )
    d1 = st.sidebar.number_input("Distancia 1", 0, 50, 10)
    d2 = st.sidebar.number_input("Distancia 2", 0, 50, 15)
    title = st.sidebar.text_input("Título personalizado")

    plot_football_passes(df, down, distance_type, d1, d2, title)
